### ISSUE TITLE
proxy authentication

### ISSUE THREAD

**Issue by salemG88** [a-dev1412/a-dev1412.github.io#1]
please how to add proxy authentication (user:pass) if there is not
add this option on this great app 
thank you

**Comment by a-dev1412** [comment]
thank you for your suggestion, we will work on it for next upcoming updates
dont forget to visit and share our link with your friends and family :)

**Comment by a-dev1412** [comment]
@salemG88 
for now, if u want to authenticate your proxy, just modify your header request
if you are using SSH/VPN, the default header request is  like this :
CONNECT [host_port] [protocol][crlf][crlf]

what u need is, first encode your proxy username and password with base64 encoding
proxy username and password is separated by colon, for example :
assume my proxy username is **adev1412** and my password is **mypassword**
go to https://www.base64encode.org/ , put **adev1412:mypassword** to the encoder
then the result will be like this : **YWRldjE0MTI6bXlwYXNzd29yZA==**
then you can modify your header request like this :
CONNECT [host_port] [protocol][crlf]**Proxy-Authorization: Basic YWRldjE0MTI6bXlwYXNzd29yZA==**[crlf][crlf]
